mutation inventoryBulkToggleActivation($inventoryItemId: ID!, $inventoryItemUpdates: [InventoryBulkToggleActivationInput!]!) {
    inventoryBulkToggleActivation(inventoryItemId: $inventoryItemId, inventoryItemUpdates: $inventoryItemUpdates) {
        inventoryItem {
            id
        }
        inventoryLevels {
            id
            quantities(names: ["available"]) {
                name
                quantity
            }
            location {
                id
            }
        }
        userErrors {
            field
            message
            code
        }
    }
}

# {
#  "inventoryItemId": "gid://shopify/InventoryItem/30322695",
#  "inventoryItemUpdates": [
#    {
#      "locationId": "gid://shopify/Location/648019273",
#      "activate": true
#    }
#  ]
#}