query {
    inventoryLevel(id: "gid://shopify/InventoryLevel/523463154?inventory_item_id=30322695") {
        id
        quantities(names: ["available", "incoming", "committed", "damaged", "on_hand", "quality_control", "reserved", "safety_stock"]) {
            name
            quantity
        }
        item {
            id
            sku
        }
        location {
            id
            name
        }
    }
}