[tool.poetry]
name = "bubble-motor"
version = "0.1.0"
description = ""
authors = ["thnkr-one <jacob@thnk.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
