mutation collectionAddProductsV2($id: ID!, $productIds: [ID!]!) {
    collectionAddProductsV2(id: $id, productIds: $productIds) {
        job {
            done
            id
        }
        userErrors {
            field
            message
        }
    }
}

# {
#  "id": "gid://shopify/Collection/636030761",
#  "productIds": [
#    "gid://shopify/Product/-1",
#    "gid://shopify/Product/108828309",
#    "gid://shopify/Product/-2"
#  ]
#}