mutation collectionPublish($input: CollectionPublishInput!) {
    collectionPublish(input: $input) {
        collection {
            # Collection fields
        }
        collectionPublications {
            # CollectionPublication fields
        }
        shop {
            # Shop fields
        }
        userErrors {
            field
            message
        }
    }
}