# k8s/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: bubble-auth-secret
type: Opaque
stringData:
  SECRET_KEY: "<your-secret-key>"
  JWT_SECRET_KEY: "<your-jwt-secret-key>"
  DATABASE_NAME: "<your-supabase-database-name>"
  DATABASE_USER: "<your-supabase-database-user>"
  DATABASE_PASSWORD: "<your-supabase-database-password>"
  DATABASE_HOST: "<your-supabase-database-host>"
  DATABASE_PORT: "6543"  # Supabase default port
  ALLOWED_HOSTS: "your-domain.com"
  GS_BUCKET_NAME: "<your-gcs-bucket-name>"
  GOOGLE_APPLICATION_CREDENTIALS_JSON: |
    {
      "type": "service_account",
      "project_id": "<your-gcp-project-id>",
      "private_key_id": "<your-private-key-id>",
      "private_key": "<your-private-key>",
      "client_email": "<your-service-account-email>",
      "client_id": "<your-client-id>",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "<your-cert-url>"
    }
